import Draft from './mapParts/Draft'
import SideTeams from './mapParts/Sides'
import PicksBans from './mapParts/PickBan'
import { FirstBlood, PlacesFirstBlood } from './mapParts/objectives/FirstBlood'
import FirstTower from './mapParts/objectives/FirstTower'
import { FirstHerald, SecondHerald, HeraldRoute } from './mapParts/objectives/Herald'
import { FirstDrake, SecondDrake, ThirdDrake, DrakeType } from './mapParts/objectives/Drake'
import KDA from './mapParts/finalStats/KDA'
import TotalGold from './mapParts/finalStats/TotalGold'
import DamageTaken from './mapParts/finalStats/DamageTaken'
import DamageDealt from './mapParts/finalStats/DamageDealt'
class MapRequest implements Draft, 
                            PicksBans, 
                            SideTeams, 
                            FirstBlood, 
                            FirstTower, 
                            FirstHerald, 
                            SecondHerald, 
                            FirstDrake, 
                            SecondDrake, 
                            ThirdDrake, 
                            KDA, 
                            TotalGold, 
                            DamageTaken, 
                            DamageDealt, 
                            DamageDealt {

    constructor(
        public winner: 'team1' | 'team2',
        public winner_side: 'blue' | 'red',
        public length: string,
        public blue_side: number,
        public red_side: number,
        public blue_baron_player: number,
        public blue_jungle_player: number,
        public blue_mid_player: number,
        public blue_dragon_player: number,
        public blue_sup_player: number,
        public red_baron_player: number,
        public red_jungle_player: number,
        public red_mid_player: number,
        public red_dragon_player: number,
        public red_sup_player: number,
        public blue_pick_1: number,
        public blue_pick_2: number,
        public blue_pick_3: number,
        public blue_pick_4: number,
        public blue_pick_5: number,
        public red_pick_1: number,
        public red_pick_2: number,
        public red_pick_3: number,
        public red_pick_4: number,
        public red_pick_5: number,
        public blue_baron_pick: number,
        public blue_jungle_pick: number,
        public blue_mid_pick: number,
        public blue_dragon_pick: number,
        public blue_sup_pick: number,
        public red_baron_pick: number,
        public red_jungle_pick: number,
        public red_mid_pick: number,
        public red_dragon_pick: number,
        public red_sup_pick: number,
        public patch: string = '3.5a',
        public blue_turrets_destroyed: number = 0,
        public red_turrets_destroyed: number = 0,
        public blue_ban_1?: number,
        public blue_ban_2?: number,
        public blue_ban_3?: number,
        public blue_ban_4?: number,
        public blue_ban_5?: number,
        public red_ban_1?: number,
        public red_ban_2?: number,
        public red_ban_3?: number,
        public red_ban_4?: number,
        public red_ban_5?: number,
        public vod_link?: string,
        public id?: number,
        public team_first_blood?: number,
        public team_first_death?: number,
        public player_first_blood?: number,
        public player_first_death?: number,
        public place_first_blood?: PlacesFirstBlood,
        public team_first_tower?: number,
        public first_tower_route?: 'baron' | 'mid' | 'dragon',
        public first_tower_herald?: boolean,
        public team_first_herald?: number,
        public first_herald_teamfight?: boolean,
        public first_herald_stealed?: boolean,
        public first_herald_route?: HeraldRoute,
        public team_second_herald?: number,
        public second_herald_teamfight?: boolean,
        public second_herald_stealed?: boolean,
        public second_herald_route?: HeraldRoute,
        public team_first_drake?: number,
        public first_drake_teamfight?: boolean,
        public first_drake_stealed?: boolean,
        public first_drake_type?: DrakeType,
        public team_second_drake?: number,
        public second_drake_teamfight?: boolean,
        public second_drake_stealed?: boolean,
        public second_drake_type?: DrakeType,
        public team_third_drake?: number,
        public third_drake_teamfight?: boolean,
        public third_drake_stealed?: boolean,
        public third_drake_type?: DrakeType,
        public blue_baron_kills: number = 0,
        public blue_jungle_kills: number = 0,
        public blue_mid_kills: number = 0,
        public blue_dragon_kills: number = 0,
        public blue_sup_kills: number = 0,
        public blue_baron_deaths: number = 0,
        public blue_jungle_deaths: number = 0,
        public blue_mid_deaths: number = 0,
        public blue_dragon_deaths: number = 0,
        public blue_sup_deaths: number = 0,
        public blue_baron_assists: number = 0,
        public blue_jungle_assists: number = 0,
        public blue_mid_assists: number = 0,
        public blue_dragon_assists: number = 0,
        public blue_sup_assists: number = 0,
        public red_baron_kills: number = 0,
        public red_jungle_kills: number = 0,
        public red_mid_kills: number = 0,
        public red_dragon_kills: number = 0,
        public red_sup_kills: number = 0,
        public red_baron_deaths: number = 0,
        public red_jungle_deaths: number = 0,
        public red_mid_deaths: number = 0,
        public red_dragon_deaths: number = 0,
        public red_sup_deaths: number = 0,
        public red_baron_assists: number = 0,
        public red_jungle_assists: number = 0,
        public red_mid_assists: number = 0,
        public red_dragon_assists: number = 0,
        public red_sup_assists: number = 0,
        public blue_baron_total_gold?: number,
        public blue_jungle_total_gold?: number,
        public blue_mid_total_gold?: number,
        public blue_dragon_total_gold?: number,
        public blue_sup_total_gold?: number,
        public red_baron_total_gold?: number,
        public red_jungle_total_gold?: number,
        public red_mid_total_gold?: number,
        public red_dragon_total_gold?: number,
        public red_sup_total_gold?: number,
        public blue_baron_dmg_taken?: number,
        public blue_jungle_dmg_taken?: number,
        public blue_mid_dmg_taken?: number,
        public blue_dragon_dmg_taken?: number,
        public blue_sup_dmg_taken?: number,
        public red_baron_dmg_taken?: number,
        public red_jungle_dmg_taken?: number,
        public red_mid_dmg_taken?: number,
        public red_dragon_dmg_taken?: number,
        public red_sup_dmg_taken?: number,
        public blue_baron_dmg_dealt?: number,
        public blue_jungle_dmg_dealt?: number,
        public blue_mid_dmg_dealt?: number,
        public blue_dragon_dmg_dealt?: number,
        public blue_sup_dmg_dealt?: number,
        public red_baron_dmg_dealt?: number,
        public red_jungle_dmg_dealt?: number,
        public red_mid_dmg_dealt?: number,
        public red_dragon_dmg_dealt?: number,
        public red_sup_dmg_dealt?: number,
    ) { }
}

export default MapRequest